# These are supported funding model platforms

github: zThana
patreon: 
open_collective: 
ko_fi: thana
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
custom: 
